### ISSUE TITLE
Release handling example isn't working

### ISSUE THREAD

**Issue by tommyvn** [rebar/rebar#291] opened 2014-05-30 12:59 UTC
I'm running Erlang 17 installed from the apt repo supplied by erlang-solutions.
I've followed https://github.com/rebar/rebar/wiki/Release-handling to the letter.
In doing so I've experienced two problems.

The first is as follows:

```
$ rebar compile generate
==> rel (compile)
==> exemplar (compile)
==> rel (generate)
ERROR: Unable to generate spec: read file info /usr/lib/erlang/man/man1/zsh5.1.gz failed
ERROR: Unexpected error: rebar_abort
ERROR: generate failed while processing /tmp/exemplar/rel: rebar_abort
```

I tracked this down to the fact that there's a link to man pages in the erlang directory which rebar seems to be looping thru. One of the zsh man pages on my laptop is a dead link for some unknown reason but it still seems weird that rebar is reading the man directory in the first place. Removing the man link gets rid of that error:

```
$ ls -l /usr/lib/erlang                                                                                                                                                                     ] 1:25 PM
total 20
drwxr-xr-x  2 root root 4096 Apr 23 21:22 bin
drwxr-xr-x  6 root root 4096 Apr 23 21:22 erts-6.0
drwxr-xr-x 53 root root 4096 Apr 24 15:26 lib
lrwxrwxrwx  1 root root   15 May 30 13:21 man -> ../../share/man
drwxr-xr-x  3 root root 4096 Apr 23 21:22 releases
drwxr-xr-x  4 root root 4096 Apr  9 21:54 usr
$ sudo unlink /usr/lib/erlang/man
$ rebar compile generate
==> rel (compile)
==> exemplar (compile)
==> rel (generate)
WARN:  'generate' command does not apply to directory /tmp/exemplar
```

Which brings me on to the second problem. The resulting build won't start:

```
cd rel
$ ./exemplar/bin/exemplar start
$ ./exemplar/bin/exemplar attach
Node 'exemplar@127.0.0.1' not responding to pings.
Node is not running!
$ cat exemplar/log/erlang.log.1

=====
===== LOGGING STARTED Fri May 30 10:22:36 BST 2014
=====
Exec: /tmp/exemplar/rel/exemplar/erts-6.0/bin/erlexec -boot /tmp/exemplar/rel/exemplar/releases/1/exemplar -mode embedded -config /tmp/exemplar/rel/exemplar/releases/1/sys.config -args_file /tmp/exemplar/rel/exemplar/releases/1/vm.args -- console ''
Root: /tmp/exemplar/rel/exemplar
{"init terminating in do_boot",{'cannot load',elf_format,get_files}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
```

Any ideas as to how I can fix it?

**Comment by jinuljt** [comment] 2015-02-10 03:25
rm /usr/lib/erlang/man/man1/zsh5.1.gz

and it works

**Comment by tuncer** [comment] 2015-02-12 13:22
@jinuljt I don't know why zsh5.1.gz would end up in erlang's private man1 dir. I'd suggest to ask on erlang-questions@erlang.org (or erlang-bugs@erlang.org) whether the issue is in erlang's Makefiles.

**Comment by tuncer** [comment] 2015-02-12 13:25
@jinuljt I don't know why zsh5.1.gz would end up in erlang's private man1 dir. I'd suggest to ask on erlang-questions@erlang.org (or erlang-bugs@erlang.org) whether the issue is in erlang's Makefiles.

Just a guess, but is `/usr/lib/erlang/man` a symlink to `/usr/share/man`?

**Comment by moxford** [comment] 2015-03-29 00:00
The fix for me was to explicitly ADD

**Comment by lrascao** [comment] 2017-08-21 15:54
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.

**Closed by lrascao** 2017-08-21 15:54 UTC
Labels: bug
