### ISSUE TITLE
Inconsistent behavior inside docker

### ISSUE THREAD

**Issue by ahawkins** [rebar/rebar#381] opened 2014-11-02 10:26 UTC
Hello everyone. My first time using rebar resulted in me stumbling upon a bug. In short, `rebar eunit` may or may not exit completely. In some cases it hangs after copying the src files into `.eunit`. Unfortunately this does not happen 100% off the time. It only happens occasionally. You can find the source for building the troublesome image at: https://github.com/ahawkins/docker-rebar-bug. I've also opened up a bug on docker here: https://github.com/docker/docker/issues/8910 since not sure where the fault is. You can test your setup by running: `docker run --rm -it ahawkins/rebar-bug`. The success/failure conditions are documented in the linked github repo.

**Comment by olof** [comment] 2015-05-09 16:53
After having the same issue, I played around with docker's storage backend, and that seems to be significant. I was able to reproduce with aufs backend but not with devicemapper backend. (This flag (`-s`) should be given when starting the docker service.)

**Comment by olof** [comment] 2015-05-09 16:59
Sorry, spoke too fast. It only became less reproducible: went from triggered 100% of the times to ~2/10 times.

**Comment by ferd** [comment] 2015-05-09 17:53
Would that point to a purely docker issue compared to anything else?  I'm not sure what could fix it if rebar otherwise works fine on OSX, Windows, BSD, multiple linux distros and so on.

**Comment by olof** [comment] 2015-05-10 09:36
@ferd, if that question was aimed at me, I don't feel qualified to say, but I don't think that's an unreasonable conclusion. Hard to say without knowing the root cause of this issue.

**Comment by ferd** [comment] 2015-05-10 13:43
I've marked this as a question and a bug given we're not quite sure who can fix this or if it's even our fault then.

**Comment by lrascao** [comment] 2017-08-20 17:35
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.

**Closed by lrascao** 2017-08-20 17:35 UTC
Labels: bug, question
