### ISSUE TITLE
port_compiler: does the current is_expandable logic really make sense?

### ISSUE THREAD

**Issue by cfra** [rebar/rebar#348] opened 2014-08-20 12:05 UTC
The current `is_expandable` logic in `port_compiler` judges any variable that has a default definition containing other variables as expandable. At least to me, that behavior is a bit confusing. Take for example the following default definition for `ERL_LDFLAGS`:

```
ERL_LDFLAGS = -L$ERL_EI_LIBDIR -lerl_interface -lei
```

No  matter what I export for `ERL_LDFLAGS` when calling rebar, it will always be overridden by the default definition because `ERL_LDFLAGS` is deemed expandable. Is it really intentional that the user is unable to override the default definition for `ERL_LDFLAGS`?

My suggestion would be to only treat those variables as expandable which contain themselves in their default definition. An example for this would be `CFLAGS`:

```
CFLAGS = -m64 $CFLAGS
```

Here, imho, it makes much more sense to apply the default expansion to an existing export of `CFLAGS` than for the case of `ERL_LDFLAGS`.

**Comment by bboozzoo** [comment] 2016-02-17 11:22
@tuncer this will certainly fix cross-compilation, right now I cannot override `ERL_LDFLAGS` what results in native library paths being picked up instead of the target ones. As a workaround I'm setting ERL_EI_LIBDIR as it's used in the following context:

    ERL_LDFLAGS=-L$ERL_EI_LIBDIR -lerl_interface -lei'

and is itself non-expandable. Fortunately I can override `ERL_CFLAGS`, so in the end I don't have to ship a patched version of rebar.

**Comment by lrascao** [comment] 2016-02-19 17:03
@bboozzoo could you take a look at #590 and see if it fixes your use case? I would also appreciate feedback on some other edge case that we're not covering in the added test

**Comment by lrascao** [comment] 2016-06-07 23:18
c43f2e55 reversed this proposed fix due to a regression detected for already existing projects

**Comment by lrascao** [comment] 2017-08-20 17:35
Hi, this issue was closed in an attempt to do quick basic filtering. All tickets prior to March 2017 were closed and will be reopened on a per-request basis, please give rebar3 a try and feel free to reopen if it's a pressing issue that is still unresolved.

**Closed by lrascao** 2017-08-20 17:35 UTC
Labels: question

**Comment by cfra** [comment] 2017-08-23 18:00
What is the status then? For future reference it would be really useful if the way this was addressed was documented here in the issue. If it was not addressed, leaving the issue open would make more sense, in my humble opinion.

**Comment by lrascao** [comment] 2017-08-23 21:53
There's likely no further effort being put in this ticket by the maintainers seeing as rebar2 is now deprecated, we recommend trying out rebar3 and it's port compiler plugin (https://github.com/blt/port_compiler), chances of improvements/requests being integrated are much better there.
